name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
 
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-u91wjv1bkh7wawvr.cn-qingdao.personal.cr.aliyuncs.com #注意这里
        username: xuxingxing0517
        password: Aa0517!@#
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.getcollate.io/openmetadata/db:1.5.6 docker://crpi-u91wjv1bkh7wawvr.cn-qingdao.personal.cr.aliyuncs.com/xuzy-0517/db:1.5.6
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
